<a href="https://colab.research.google.com/github/P-sys/classification-2021/blob/main/Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [21]:
ren1 = np.arange(1, 21)
two = np.ones(20, dtype=int) * 2

mat1 = two ** ren1
mat1 = np.divide(mat1, ren1, dtype=float)

mat1

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [11]:
i = np.arange(0, 6)

mat2 = sum(0.1 ** (3 * i) * 0.2 ** (4 * i))

mat2

1.00000160000256

**3.** Создать нулевую матрицу $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [30]:
mat3 = np.zeros((8,8))

mat3[::2, ::2] = 1
mat3[1::2, 1::2] = 1

mat3

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [4]:
X = np.random.random((5, 2))

x,y = X[:,0], X[:,1]
r = np.hypot(x,y)
t = np.arctan2(y,x)

pol = np.concatenate([[r] ,[t]], axis=0).T

pol

array([[0.71045551, 0.88169089],
       [0.65501759, 0.5787726 ],
       [0.50173267, 0.85508325],
       [1.03945095, 0.71404245],
       [0.13802316, 0.25881722]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [24]:
X = np.random.random((10, 10))

ind = np.unravel_index(np.argmax(X, axis=None), X.shape)

ind

(2, 0)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [47]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

dist = np.sqrt((X[:, 0] - y.item(0))**2 + (X[:, 1] - y.item(1))**2)

X[np.argmin(dist)]

array([0.42598593, 0.43490986])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [29]:
x = np.linspace(-3, 3, 100)
(x ** 2 + 2 * x + 6) * (x < 0) + (x + 6) * ((x >= 0) & (x <= 2)) + (x ** 2 + 4 * x - 4) * (x >= 2)

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [31]:
X = np.random.random((10, 10))

means = np.reshape(np.mean(X, axis=1), (-1, 1))

mat8 = X - means

np.mean(mat8, axis=1)

array([-8.88178420e-17,  1.11022302e-17,  2.22044605e-17, -1.11022302e-17,
       -3.33066907e-17, -5.55111512e-17,  3.33066907e-17, -4.44089210e-17,
        8.88178420e-17,  1.11022302e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [36]:
X = np.random.normal(loc=5, scale=2., size=1000)

print(f"Выборочное среднее {np.mean(X)}")
print(f"Выборочная дисперсия {np.var(X)}")

Выборочное среднее 5.026634074752936
Выборочная дисперсия 4.152598949604627


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [37]:
x = np.arange(5)
y = np.expand_dims(np.arange(5), axis=1)
mat10 = (x + y) % 5

mat10

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [44]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [40]:
x = np.array([50, 3, 1, 7, 20])
c = 5
ind = np.arange(len(x))

np.random.choice(ind, c, p=x/np.sum(x))

array([4, 0, 4, 0, 0])